courses/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.course_list, name='list'),
    url(r'^(?P<course_pk>\d+)/(?P<step_pk>\d+)/$', views.step_detail, name='step'),
    url(r'^(?P<pk>\d+)$', views.course_detail, name='detail'),
]

learning_site/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static

from . import views

urlpatterns = [
    url(r'^courses/', include('courses.urls', namespace='course')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index),

]

urlpatterns += staticfiles_urlpatterns()
# Checks if we r in Debug mode it add this url for static files

courses/models.py
from django.db import models


class Course(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=255)
    description = models.TextField()

    def __str__(self):
        return self.title


class Step(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    content = models.TextField(blank=True, default='')
    order = models.IntegerField(default=0)
    course = models.ForeignKey(Course)

    class Meta:
        ordering = ['order', ]

    def __str__(self):
        return self.title

courses/views.py
from django.shortcuts import render, get_object_or_404

from .models import Course, Step


def course_list(request):
    courses = Course.objects.all()
    return render(request, 'courses/course_list.html', {'courses': courses})


def course_detail(request, pk):
    course = get_object_or_404(Course, pk=pk)
    return render(request, 'courses/course_detail.html', {'course': course})


def step_detail(request, course_pk, step_pk):
    step = get_object_or_404(Step, course_id=course_pk, pk=step_pk)  # course_id is django referring to the ForeingKey
    return render(request, "courses/step_detail.html", {"step": step})

learning_site/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'home.html')

courses/templates/courses/course_detail.html
{% extends "layout.html" %}
{% load course_extras %}

{% block title %}
    {{ course.title }}
{% endblock %}

{% block content %}
    <article>
        <h2>{{ course.title }}</h2>
    </article>
    {{ course.description|makdown_to_html }}

    <section>
        {% for step in course.step_set.all %}
            <h3>
                <a href="{% url 'course:step' course_pk=step.course.pk step_pk=step.pk %}">{{ step.title }}</a>
            </h3>
            {{ step.description }}
        {% endfor %}

    </section>
{% endblock %}

courses/templates/courses/course_list.html
{% extends "layout.html" %}
{% load course_extras %}

{% block title %}
    Available
{% endblock %}

{% block content %}
    <div class="cards">
        {% for course in courses %}
            <div class="card">
                <header>
                    <a href="{% url 'course:detail' pk=course.pk %}">{{ course.title }}</a>
                </header>
                <div class="card-copy">
                   {{ course.description|makdown_to_html }}
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}

courses/templates/courses/course_nav.html
{% for course in courses %}
    <div><a href="{% url 'course:detail' pk=course.pk %}">{{ course.title }}</a></div>
{% endfor %}

courses/templates/courses/step_detail.html
{% extends "layout.html" %}
{% load course_extras %}

{% block title %}
    {{ step.title }}
{% endblock %}

{% block content %}
    <article>
        <h2><a href="{% url 'course:detail' pk=step.course.pk %}">{{ step.course.title }}</a></h2>
        <h3>{{ step.title }}</h3>
        {% with con=step.content %}
            {{ con|linebreaks }}
            Content: {{ con|wordcount }} words. Estimated time to complete: {{ con|wordcount|time_estimate }}
            minute{{ con|wordcount|time_estimate|pluralize }}.
        {% endwith %}

    </article>
{% endblock %}

templates/home.html
{% extends 'layout.html' %}

{% block title %}
    Hello there!
{% endblock %}

{% block content %}
<h1>Welcome</h1>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
{% load static from staticfiles %}
{% load course_extras %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link type="text/css" rel="stylesheet" href="{% static "css/layout.css" %}">
</head>
<body>

<div class="site-container">
    {% nav_courses_list %}
    <nav>
        <a href="#">Home</a>
        <a href="{% url 'course:list' %}">Courses</a>
    </nav>
    <p>Don't miss our latest course {% newest_course %}</p>
    {% block content %}
    {% endblock %}
</div>

</body>
</html>